### ISSUE TITLE
Row length too small

### ISSUE THREAD

**Issue by enrico3** [hsnborn22/LinGo#3] opened 2023-12-06 14:44 UTC
Hello,
not sure why but for me the rows are displayed too short (on Windows). 

This input file
![Input file](https://github.com/hsnborn22/LinGo/assets/31779179/402d9ee3-30d2-4f7d-a28b-c7ac041ec59b)

is displayed as:
![Output formatting](https://github.com/hsnborn22/LinGo/assets/31779179/cade1477-56cc-4a86-b41d-54d61816fcf4)

**Comment by hsnborn22** [comment] 2023-12-06 16:22
This issue is correlated to the first one; it is all caused by poor API communication with the windows terminal. As you can see the "current size" values are -1,-1 which is a flag I used to denote errors with the terminal size API. I'll close this issue and merge it in the first one.

**Closed by hsnborn22** 2023-12-06 16:22 UTC
